"use client";

import Link from "next/link";
import { ArrowUpRight, Clock3, FileCheck2, ShieldAlert, Sparkles, Users } from "lucide-react";
import { useDemo, statusColor } from "@/components/demo-provider";

const metrics = [{ label: "Open workload", value: "24", change: "+12%", icon: FileCheck2, color: "bg-indigo-50 text-indigo-600" }, { label: "SLA at risk", value: "03", change: "Needs attention", icon: Clock3, color: "bg-rose-50 text-rose-600" }, { label: "Escalations", value: "06", change: "Across 2 teams", icon: ShieldAlert, color: "bg-amber-50 text-amber-600" }, { label: "Resolved today", value: "38", change: "+8.4% from yesterday", icon: Users, color: "bg-emerald-50 text-emerald-600" }];

export default function OverviewPage() {
  const { cases } = useDemo();
  return <div className="app-grid min-h-screen px-5 py-7 lg:px-10 lg:py-9"><div className="mx-auto max-w-7xl">
    <header data-tour="overview-header" className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-sm font-medium text-indigo-600">Monday, October 2</p><h1 className="text-3xl font-bold tracking-tight text-slate-950">Good morning, Maya</h1><p className="mt-2 text-sm text-slate-500">Here is what needs your attention across customer operations.</p></div><Link href="/reviews" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white shadow-lg shadow-indigo-200 transition hover:bg-indigo-700">Open customer inbox <ArrowUpRight className="size-4" /></Link></header>
    <section data-tour="overview-metrics" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => <article key={metric.label} className="metric-glow rounded-2xl border border-white bg-white p-5"><div className="mb-5 flex items-start justify-between"><div className={`grid size-10 place-items-center rounded-xl ${metric.color}`}><metric.icon className="size-5" /></div><span className="text-xs font-medium text-slate-400">{metric.change}</span></div><p className="text-3xl font-bold tracking-tight">{metric.value}</p><p className="mt-1 text-sm text-slate-500">{metric.label}</p></article>)}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]"><div data-tour="priority-queue" className="rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b px-6 py-5"><div><h2 className="font-semibold">Priority queue</h2><p className="mt-1 text-xs text-slate-500">Cases requiring a response in the next two hours</p></div><Link href="/reviews" className="text-sm font-semibold text-indigo-600">View all</Link></div><div className="divide-y">{cases.slice(0, 4).map((item) => <Link href={`/reviews/${item.id}`} key={item.id} className="flex items-center gap-3 px-6 py-4 transition hover:bg-slate-50"><div className="grid size-10 shrink-0 place-items-center rounded-full bg-slate-100 text-xs font-bold text-slate-600">{item.customer.initials}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold">{item.customer.name}</p><span className={`rounded-md px-2 py-0.5 text-[10px] font-bold ring-1 ring-inset ${statusColor(item.status)}`}>{item.status}</span></div><p className="mt-1 truncate text-xs text-slate-500">{item.subject}</p></div><div className="text-right"><p className={item.sla === "At risk" ? "text-xs font-bold text-rose-600" : "text-xs font-medium text-slate-500"}>{item.sla}</p><p className="mt-1 text-[11px] text-slate-400">{item.receivedAt}</p></div></Link>)}</div></div>
      <div data-tour="ai-intelligence" className="rounded-2xl bg-slate-900 p-6 text-white"><div className="flex items-center justify-between"><div><p className="flex items-center gap-2 text-sm font-semibold text-indigo-200"><Sparkles className="size-4" />SupportOS intelligence</p><h2 className="mt-3 text-xl font-semibold">AI is keeping the queue moving.</h2></div><div className="grid size-11 place-items-center rounded-xl bg-white/10"><Sparkles className="size-5 text-violet-200" /></div></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-4"><p className="text-2xl font-semibold">94.2%</p><p className="mt-1 text-xs text-slate-300">Intent accuracy</p></div><div className="rounded-xl bg-white/10 p-4"><p className="text-2xl font-semibold">8.6h</p><p className="mt-1 text-xs text-slate-300">Hours saved today</p></div></div><div className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4"><p className="text-sm font-medium">3 cases need human judgment</p><p className="mt-1 text-xs leading-5 text-slate-300">Payment disputes and identity changes have been routed for review.</p></div><Link href="/ai-operations?tab=workflow" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-indigo-200">Explore AI operations <ArrowUpRight className="size-4" /></Link></div></section>
    <Link data-tour="workflow-entry" href="/ai-operations?tab=workflow" className="mt-6 flex items-center justify-between gap-5 rounded-2xl border border-indigo-200 bg-gradient-to-r from-indigo-600 to-violet-600 p-5 text-white shadow-xl shadow-indigo-200 transition hover:-translate-y-0.5 hover:shadow-2xl"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-indigo-100"><Sparkles className="size-3.5" />Interactive demo</p><h2 className="mt-2 text-lg font-bold">Explore the Agent Workflow</h2><p className="mt-1 text-sm text-indigo-100">See how specialized agents turn an incoming email into a review-ready customer case.</p></div><span className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-indigo-700">Open workflow <ArrowUpRight className="size-4" /></span></Link>
  </div></div>;
}
